### ISSUE TITLE
Side scrolling of data is inconvenient

### ISSUE THREAD

**Issue by vinayoommen** [1hf/StudentHub#4]
When we requested for side scrolling, we wanted side scrolling from person to person, that is next student, previous student based on the selection. 
What was changed was the side scrolling of data within each students data which is very inconvenient. Please roll back to vertical scrolling as was done before.

**Comment by prabagar-mk** [comment]
The scrolling is added to the student details page.
The left and right scrolling shows the next and previous student details now.
