### ISSUE TITLE
Faculty/student first login

### ISSUE THREAD

**Issue by vinayoommen** [1hf/StudentHub#8]
The best mechanism for faculty and students has to be formulated

**Comment by vinayoommen** [comment]
Arun will connect with Vasanth and import e-learning user name and passwords for this.

**Comment by vinayoommen** [comment]
This will be a one time pull from e-learning to the database. 
Student can change password on the app.

**Comment by vinayoommen** [comment]
New downloader has an option to register/login
user enters the id and phone number which is checked against the database. 
If success, OTP is sent, if failed, send to form. 
Customer support form. 
Super admin can reset the password sent to the reg mobile number

**Comment by prabagar-mk** [comment]
The forgot password option is added to the app. Please find the flow below.
The user will click the forgot password button in the login screen and this will open the form where the student/faculty has to enter the userid and the mobile number.
If the userid and mobile number combo is correct an OTP message will be sent to the registered mobile number and the otp text box will be enabled.
The user can enter the received otp and submit.
A new password will be generated and will be sent to the user to his/her mobile number.
After logging in, the user can change the password going into the account page.
